spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ed243e77fb784c4aa7f4b62c5ca258f9
            client-secret: fe9ecd664670429586a3805974ff06bf
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000
            scope:
              - user-read-currently-playing
              - user-modify-playback-state
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize?
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: display_name